### ISSUE TITLE
[Docs] - Create contributing file

### ISSUE THREAD

**Issue by saifabusaleh** [saifabusaleh/clipboard-history-extension#22]
1- Follow this [guide](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors#adding-a-contributing-file) to create contributing.md file under root directory.

2- move [Development environment section](https://github.com/saifabusaleh/clipboard-history-extension#development-environment) from README.md to the new contributing.md file

**Comment by fcoiuri** [comment]
Hi, can I work on this issue?
