### ISSUE TITLE
Find better icons to the extension

### ISSUE THREAD

**Issue by saifabusaleh** [saifabusaleh/clipboard-history-extension#5]
The current icon is so small

Find better icon to the extension that is related to the extension functionality (the extension saves copied text in browser), so looking for something like scissor icon

with 128, 256, 512 sizes 

 and update it in `manifest.json` and `icons` directory 

Follow the getting started guide in README to find out more how to contribute to project

**Comment by MonarthS** [comment]
@saifabusaleh can you check [#7](https://github.com/saifabusaleh/clipboard-history-extension/pull/7)?

**Comment by MonarthS** [comment]
@saifabusaleh can you assign this to me & check [#7](https://github.com/saifabusaleh/clipboard-history-extension/pull/7)?

**Comment by saifabusaleh** [comment]
hi @MonarthS @ad-dan

I have checked both of your pull requests and it look like the icons not relevant the extension

The extension saves copied text in browser in it, looking here for more specific icons related to copying/clipping, etc..

For example icons like scissor would be good

@MonarthS If you want to replace it and look for icons i can assign to you
