### ISSUE TITLE
[Possible bug report] Clicking clear saved text only clears it when reopening extension 

### ISSUE THREAD

**Issue by zurda** [saifabusaleh/clipboard-history-extension#9]
### What's happening 

When the extension has saved text, clicking the `Clear saved text` button doesn't clear the text immediately. Instead, the text is cleared when closing and reopening the extension. 

### Desired behaviour

Clear the text on click or show some kind of feedback for better user experience. 

![possible-bug-report](https://user-images.githubusercontent.com/16784959/95663143-78556780-0b34-11eb-9ebb-ab4d43d956ac.gif)

### Suggested solution

Render an empty list after clicking the reest button: 

```
const onResetClick = () => {
    chrome.runtime.sendMessage({ clear: true });
    renderClippings(); // ---> add this line 
}
```

Apologies if I'm missing something and this is something that no one else experienced. Feel free to close if that is the case

Happy to pick this up if the suggested solution makes sense

**Comment by saifabusaleh** [comment]
Hi @zurda 

You are right, good catch.
